const models1 = {
  acura: [
    "CL",
    "ILX",
    "ILX Hybrid",
    "Integra",
    "legend",
    "mdx",
    "nsx",
    "rdx",
    "rl",
    "rlx",
    "slx",
    "tl",
    "tlx",
    "tsx",
    "tsx sport Wagon",
    "Vigor",
    "Zdx",
  ],
  alfa_romeo: ["4c", "giulia", "stelvio"],
  am_general: ["Hummer"],
  aston_martin: [
    "DB11",
    "DB7",
    "DB9",
    "DB9GT",
    "DBS",
    "DBS Superlegger",
    "DBX",
    "Rapide",
    "Rapide AMR",
    "Rapide S",
    "V12 Vanquish",
    "V12 Vantage",
    "V12 Vantage S",
    "V8 Vantage",
    "Vanquish S",
    "Ventage",
    "Virage",
  ],
  audi: [
    "100",
    "200",
    "80",
    "90",
    "A3",
    "A3 Sportback e-tron",
    "A4",
    "A4 Allroad",
    "A5",
    "A6",
    "A6 Allroad",
    "A7",
    "A8",
    "Allroad",
    "Allroad quattro",
    "Cabriolet",
    "Coupe",
    "Etron",
    "Etron sportback",
    "Q3",
    "Q5",
    "Q7",
    "Q8",
    "R8",
    "RS 3",
    "RS 4",
    "RS 5",
    "RS 6",
    "RS 7",
    "RS Q8",
    "S1",
    "S2",
    "S3",
    "S4",
    "S5",
    "S6",
    "S7",
    "S8",
    "SQ 5",
    "SQ 7",
    "SQ 8",
    "TT RS",
    "TTS",
    "V8",
  ],
  bentley: [
    "Azure",
    "Arnage",
    "Bentayga",
    "Brooklands",
    "Continental",
    "Continental Flying Spur",
    "Continental Flying Spur Speed",
    "Continental GT",
    "Continental GT Speed",
    "Continental GT SPeed Covertible",
    "Continental GT3-R",
    "Continental GTC",
    "Continental GTC Speed",
    "Continental Supersports",
    "Continental Supersports Covertible",
    "Flying Spur",
    "Mulsanne",
    "Supersports Convertible ISR",
  ],
  bmw: [
    "1 Series",
    "2 Series",
    "2 Series Gran Coupe",
    "3 Series",
    "3 Series Gran Turismo",
    "4 Series",
    "4 Series Gran Coupe",
    "5 Series",
    "5 Series Gran Coupe",
    "6 Series",
    "6 Series Gran Coupe",
    "5 Series Gran Turismo",
    "7 Series",
    "8 Series",
    "8 Series Gran Coupe",
    "ActiveHybrid 5",
    "ActiveHybrid 7",
    "ActiveHybrid X6",
    "Alpina",
    "ALPINA B6 Gran Coupe",
    "ALPINA B7",
    "i3",
    "i8",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "Z3",
    "Z4",
    "Z8",
  ],
  bugatti: ["Veyron 16.4"],
  buick: [
    "Cascada",
    "Century",
    "Electra",
    "Enclave",
    "Encore",
    "Encore GX",
    "Envision",
    "Estate Wagon",
    "LaCrosse",
    "LeSabre",
    "Lucerne",
    "Park Avenue",
    "Rainier",
    "Reatta",
    "Regal",
    "Regal Sportback",
    "Regal TourX",
    "Rendezvous",
    "Riviera",
    "Roadmaster",
    "Skylark",
    "Terraza",
    "Verano",
  ],
  cadillac: [
    "Allante",
    "ATS",
    "ATS coupe",
    "ATS-V",
    "Brougham",
    "Catera",
    "CT4",
    "CT5",
    "CT6",
    "CT6-V",
    "CTS",
    "CTS Coupe",
    "CTS Wagon",
    "CTS-V",
    "CTS-V Coupe",
    "CTS-V Wagon",
    "DeVille",
    "DTS",
    "Eldorado",
    "ELR",
    "Escalade",
    "Escalade ESV",
    "Escalade Hybrid",
    "Fleetwood",
    "Seville",
    "Sixty Special",
    "SRX",
    "STS",
    "STS-V",
    "XLR",
    "XLR-V",
    "XT4",
    "XT5",
    "XT6",
    "XTS",
  ],
  chevrolet: [
    "Astro",
    "Astro Cargo",
    "Avalanche",
    "Aveo",
    "Beretta",
    "Black Diamond Avalanche",
    "Blezer",
    "Bolt EV",
    "C/K 1500 Series",
    "C/K 2500 Series",
    "C/K 3500 Series",
    "Camaro",
    "Caprice",
    "Captiva Sport",
    "Cavalier",
    "Celebrity",
    "Chevy Van",
    "Chevy Van Classic",
    "City Express",
    "Classic",
    "Cobalt",
    "Colorado",
    "Corsica",
    "Corvette",
    "Cruze",
    "Cruze Limited",
    "Equinox",
    "Express",
    "Express Cargo",
    "HHR",
    "Impala",
    "Imapala Limited",
    "Lumina",
    "Lumina Minivan",
    "Malibu",
    "Malibu Classic",
    "Malibu Hybrid",
    "Malibu Limited",
    "Malibu Maxx",
    "Metro",
    "Monte Carlo",
    "Prizm",
    "R/V 350 Series",
    "S-10",
    "S-10 Blazer",
    "Silverado",
    "Silverado 1500",
    "Silverado 1500 Classic",
    "Silverado 1500 Hybrid",
    "Silverado 1500 LD",
    "Silverado 1500 HD",
    "Silverado 1500 HD Classic",
    "Silverado 2500",
    "Silverado 2500 HD",
    "Silverado 2500 HD Classic",
    "Silverado 3500 Classic",
    "Silverado 3500 HD",
    "Sonic",
    "SPark",
    "Spark EV",
    "Sportvan",
    "SS",
    "SSR",
    "Suburan",
    "Tahoe",
    "Tracker",
    "TrailerBlezar",
    "TrailerBlezar EXT",
    "Traverse",
    "Trax",
    "Uplander",
    "Venture",
    "Volt",
  ],
  chrysler: [
    "200",
    "300",
    "300M",
    "Aspen",
    "Cirrus",
    "Concorde",
    "Crossfire",
    "Grand Voyager",
    "Imperial",
    "Le Baron",
    "LHS",
    "New Yorker",
    "Pacifica",
    "Pacifica Hybrid",
    "Prowler",
    "PT Cruiser",
    "Sebring",
    "TC",
    "Town and Country",
    "Voyager",
  ],
  daewoo: ["Lanos", "Leganza", "Nubira"],
  dodge: [
    "Avenger",
    "Caliber",
    "Caravan",
    "Challenger",
    "Charger",
    "Colt",
    "Dakota",
    "Dart",
    "Daytona",
    "Durango",
    "Dyansty",
    "Grand Caravan",
    "Intrepid",
    "Journey",
    "Magnum",
    "Moaco",
    "Neon",
    "Nitro",
    "Omni",
    "RAM 150",
    "RAM 250",
    "RAM 350",
    "RAM 50 Pickup",
    "RAM Cargo",
    "RAM Pickup 1500",
    "RAM Pickup 2500",
    "RAM Van",
    "RAM Wagon",
    "RAM Charger",
    "Shadow",
    "Spirit",
    "Sprinter",
    "Sprinter Cargo",
    "SRT Viper",
    "Stealth",
    "Stratus",
    "Viper",
  ],
  eagle: ["Premier", "Summit", "Talon", "Vision"],
  ferrari: [
    "360",
    "430 Scuderia",
    "456 M",
    "458 Italia",
    "488 GTv",
    "488 Spider",
    "550",
    "575M",
    "599",
    "612 Scaglietti",
    "812 Superfast",
    "California",
    "California T",
    "Enzo",
    "F12 Berlinetta",
    "F430",
    "FF",
    "GTC4Lusso",
    "Portofino",
    "Superamerica",
  ],
  lamborghini: [
    "Aventador",
    "Diablo",
    "Gallardo",
    "Huracan",
    "Murcielago",
    "Reventon",
    "Urus",
  ],
  landrover: [
    "Defender",
    "Discovery",
    "Discover Sport",
    "Freelander",
    "LR2",
    "LR3",
    "LR4",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sports",
    "Range Rover Velar",
  ],
  lexus: [
    "CT",
    "ES",
    "GS",
    "GX",
    "HS",
    "IS",
    "LS",
    "LFA",
    "LS",
    "LX",
    "NX",
    "RC",
    "RX",
    "SC",
    "UX",
  ],
  lincoln: [
    "Aviator",
    "Blackwood",
    "Continental",
    "Corsair",
    "LS",
    "Mark LT",
    "Mark VII",
    "Mark VIII",
    "MKC",
    "MKS",
    "MKT",
    "MKX",
    "MKZ",
    "Nautilus",
    "Navigator",
    "Navigator L",
    "Town Car",
    "Zephyr",
  ],
  lotus: ["Elise", "Esprit", "Evora", "Evora 400", "Evora GT", "Exige"],
  maserati: [
    "Coupe",
    "Ghibli",
    "Gran Sport",
    "Gran Turismo",
    "Gran Turismo Convertible",
    "Levante",
    "Quattroporte",
    "Spyder",
  ],
  maybach: ["57", "62", "Landaulet"],
  mazda: [
    "2",
    "3",
    "323",
    "5",
    "6",
    "626",
    "929",
    "B-Series Pickup",
    "B-Series Truck",
    "CX-3",
    "CX-30",
    "CX-5",
    "CX-7",
    "CX-9",
    "Mazdaspeed 3",
    "Mazdaspeed 6",
    "Mazdaspeed MX-5 Miata",
    "Mazdaspeed 3 Protege",
    "Millenia",
    "MPV",
    "MX-3",
    "MX-5 Miata",
    "MX-5 Miata RF",
  ],
  mclaren: [
    "5",
    "6",
    "626",
    "929",
    "B-Series Pickup",
    "B-Series Truck",
    "CX-3",
    "CX-30",
    "CX-5",
    "CX-7",
    "CX-9",
    "Mazdaspeed 3",
    "Mazdaspeed 6",
    "Mazdaspeed MX-5 Miata",
    "Mazdaspeed 3 Protege",
    "Millenia",
    "MPV",
    "MX-3",
    "MX-5 Miata",
    "MX-5 Miata RF",
  ],
  mercedez_benz: [
    "A-Class",
    "AMG GT",
    "B-Class Electric Drive",
    "C-Class predecessor W201 190",
    "C-Class",
    "CL-Class",
    "CLA-Class",
    "CLK-Class",
    "CLS-Class",
    "E-Class predecessor W124",
    "E-Class",
    "G-Class",
    "GL-Class",
    "GLA-Class",
    "GLB-Class",
    "GLC-Class",
    "GLC-Class Coupe",
    "GLE-Class",
    "GLE-Class Coupe",
    "GLK-Class",
    "GLS-Class",
    "Maybach",
    "Metris",
    "M-Class",
    "R-Class",
    "S-Class predecessor W126",
    "S-Class predecessor W140",
    "S-Class",
    "SL-Class predecessor W129",
    "SL-Class",
    "SLC-Class",
    "SLK-Class",
    "SLR McLaren",
    "SLS AMG",
    "SLS AMG GT",
    "SLS AMG GT Final Edition",
    "Sprinter",
    "Sprinter Worker",
  ],
  mercury: [
    "Capri",
    "Cougar",
    "Grand Marquis",
    "Marauder",
    "Mariner",
    "Mariner Hybrid",
    "Milan",
    "Milan Hybrid",
    "Montego",
    "Monterey",
    "Mountaineer",
    "Mystique",
    "Sable",
    "Topaz",
    "Tracer",
    "Villager",
  ],
  mini: [
    "Clubman",
    "Convertible",
    "Cooper",
    "Cooper Clubman",
    "Cooper Countryman",
    "Cooper Coupe",
    "Cooper Paceman",
    "Cooper Roadster",
    "Countryman",
    "Hardtop 2 Door",
    "Hardtop 4 Door",
  ],
  ram: [
    "1500",
    "1500 Classic",
    "2500",
    "3500",
    "C/V",
    "Dakota",
    "Promaster Cargo Van",
    "Promaster City",
    "Promaster Window Van",
  ],
  porsche: [
    "718 Boxster",
    "718 Cayman",
    "911",
    "928",
    "944",
    "968",
    "Boxster",
    "Carrera GT",
    "Cayenne",
    "Cayenne Coupe",
    "Cayman",
    "Macan",
    "Panamera",
    "Taycan",
  ],
  polestar: ["1", "2"],
  pontiac: [
    "6000",
    "Aztek",
    "Bonneville",
    "Firebird",
    "G3",
    "G5",
    "G6",
    "G8",
    "Grand Am",
    "Grand Prix",
    "GTO",
    "Le Mans",
    "Montana",
    "Montana SV6",
    "Solstice",
    "Sunbird",
    "Sunfire",
    "Torrent",
    "Trans Sport",
  ],
  plymouth: [
    "Acclaim",
    "Breeze",
    "Colt",
    "Grand Voyager",
    "Horizon",
    "Laser",
    "Neon",
    "Prowler",
    "Sundance",
    "Voyager",
  ],
  panoz: ["Esperante"],
  oldsmobile: [
    "Achieva",
    "Alero",
    "Aurora",
    "Bravada",
    "Ciera",
    "Custom Cruiser",
    "Cutlass",
    "Cutlass Calais",
    "Cutlass Ciera",
    "Cutlass Supreme",
    "Eighty-Eight",
    "Eighty-Eight Royale",
    "Intrigue",
    "LSS",
    "Ninety-Eight",
    "Regency",
    "Silhouette",
    "Toronado",
  ],
  nissan: [
    "200SX",
    "240SX",
    "300ZX",
    "350Z",
    "370Z",
    "Altima",
    "Altima Hybrid",
    "Armada",
    "Axxess",
    "Cube",
    "Frontier",
    "GT-R",
    "Juke",
    "Kicks",
    "Leaf",
    "Maxima",
    "Murano",
    "Murano CrossCabriolet",
    "NV Cargo",
  ],
  mitsubishi: [
    "3000GT",
    "Diamante",
    "Eclipse",
    "Eclipse Cross",
    "Eclipse Spyder",
    "Endeavor",
    "Expo",
    "Galant",
    "i-MiEV",
    "Lancer",
    "Lancer Evolution",
    "Lancer Sportback",
    "Mighty Max Pickup",
    "Mirage",
    "Mirage G4",
    "Montero",
    "Montero Sport",
    "Outlander",
    "Outlander PHEV",
  ],
  volvo: [
    "240",
    "740",
    "760",
    "780",
    "850",
    "940",
    "960",
    "C30",
    "C70",
    "Coupe",
    "S40",
    "S60",
    "S60 Cross Country",
    "S70",
    "S80",
    "S90",
    "V40",
    "V50",
    "V60",
    "V60 Cross Country",
    "V70",
    "V90",
    "V90 Cross Country",
    "XC",
    "XC40",
    "XC60",
    "XC70",
    "XC90",
  ],
  volkswagen: [
    "Arteon",
    "Atlas",
    "Atlas Cross Sport",
    "Beetle",
    "Beetle Convertible",
    "Cabrio",
    "Cabriolet",
    "CC",
    "Corrado",
    "e-Golf",
    "Eos",
    "Eurovan",
    "Fox",
    "Golf",
    "Rabbit",
    "Golf Alltrack",
    "Golf GTI",
    "Rabbit GTI",
    "Golf R32",
    "Golf R",
    "Golf SportWagen",
    "IO 4",
    "Jetta",
    "Jetta GLI",
    "Jetta Hybrid",
    "Jetta SportWagen",
    "New Beetle",
    "Passat",
    "Phaeton",
    "Routan",
    "Tiguan",
    "Tiguan Limited",
    "Touareg",
    "Vanagon",
  ],
  toyota: [
    "4Runner",
    "86",
    "Avalon",
    "Avalon Hybrid",
    "C-HR",
    "Camry",
    "Camry Hybrid",
    "Camry Solara",
    "Calica",
    "Corolla",
    "Corolla Hatchback",
    "Corolla Hybrid",
    "Corolla iM",
    "Cressida",
    "ECHO",
    "FJ Cruiser",
    "GR Supra",
    "Highlander",
    "Highlander Hybrid",
    "Land Cruiser",
    "Matrix",
    "Mirai",
    "MR2",
    "MR2 Spyder",
    "Paseo",
    "Pickup",
    "Previa",
    "Prius",
    "Prius C",
    "Prius Plug-in",
    "Prius Prime",
    "Prius v",
    "RAV4",
    "RAV4 EV",
    "RAV4 Hybrid",
    "RAV4 Prime",
    "Sequoia",
    "Sienna",
    "Supra",
    "T100",
    "Tacoma",
    "Tercel",
    "Tundra",
    "Venza",
    "Yaris",
    "Yaris Hatchback",
    "Yaris iA",
  ],
  tesla: ["Model 3", "Model S", "Model X", "Model Y", "Roadster"],
  suzuki: [
    "Aerio",
    "Equator",
    "Esteem",
    "Forenza",
    "Grand Vitara",
    "Kizashi",
    "Reno",
    "Samurai",
    "Sidekick",
    "Swift",
    "SX4",
    "Verona",
    "Vitara",
    "X-90",
    "XL-7",
    "XL7",
  ],
  subaru: [
    "Ascent",
    "B9 Tribeca",
    "Baja",
    "BRZ",
    "Crosstrek",
    "Forester",
    "Impreza",
    "Impreza WRX",
    "Justy",
    "Legacy",
    "Loyal",
    "Outback",
    "SVX",
    "Tribeca",
    "XT",
    "XV Crosstrek",
  ],
  spyker: ["C8"],
  smart: ["EQ Fortwo", "Fortwo"],
  scion: ["FR-S", "iA", "iM", "iQ", "tC", "xA", "xB", "xD"],
  saturn: [
    "Astra",
    "Aura",
    "Aura Hybrid",
    "ION",
    "L-Series",
    "Outlook",
    "Relay",
    "S-Series",
    "Sky",
    "VUE",
    "VUE Hybrid",
  ],
  saab: ["9-2X", "9-3", "9-3 Griffin", "9-4X", "9-5", "9-7X", "900", "9000"],
  rolls_royce: [
    "Corniche",
    "Cullinan",
    "Dawn",
    "Ghost",
    "Park Ward",
    "Phantom",
    "Phantom Coupe",
    "Phantom Drophead Coupe",
    "Silver Seraph",
    "Wraith",
  ],
  fiat: ["124 Spider", "500", "500E", "500L", "500X"],
  fisker: ["Karma"],
  ford: [
    "Aerostar",
    "Aspire",
    "Bronco",
    "Bronco ll",
    "Bronco Sport",
    "C-Max energi",
    "C-Max Hybrid",
    "Contour",
    "Crown Victoria",
    "E-150",
    "E-250",
    "E-350",
    "E-Series Van",
    "E-Series Wagon",
    "Econoline Cargo",
    "Econoline Wagon",
    "EcoSport",
    "Edge",
    "Escape",
    "EScape Hybrid",
    "Escape Plug-in HYbrid",
    "Escort",
    "Excursion",
    "Expedition",
    "Expedition EL",
    "Explorer",
    "Explorer Sport",
    "Explorer Sport Trac",
    "F-150",
    "F-150 Heritage",
    "F-250",
    "F-250 Superduty",
    "F-350",
    "f-350 SuperDuty",
    "F-450 SuperDuty",
    "Festiva",
    "Fiesta",
    "Five HUndred",
    "Flex",
    "Focus",
    "Freestar",
    "Freestyle",
    "Fusion",
    "Fusion energi",
    "Fusion HYbrid",
    "GT",
    "LTD Crown Victoria",
    "Mustang",
    "MUstang Mach-E",
    "Probe",
    "Ranger",
    "Shelby GT 350",
    "Shelby GT 500",
    "Taurus",
    "Taurus X",
    "Tempo",
    "Thunderbird",
    "Transit Connect",
    "Transit Van",
    "Transit Wagon",
    "Transit Crago Van",
    "Transit Crew Van",
    "Transit Passenger Van",
    "Windstar",
    "windstar cargo",
  ],
  genesis: ["G70", "g80", "g90", "gv80"],
  geo: ["metro", "prizm", "storm", "tracker"],

  kia: [
    "Amanti",
    "Borrego",
    "Cadenza",
    "Carnival",
    "Forte",
    "K5",
    "K900",
    "Niro",
    "Niro EV",
    "Niro Plug-In-Hybrid",
    "Optima",
    "Optima Hybrid",
    "Optima Plug-In-Hybrid",
    "Rio",
    "Rondo",
    "Sedona",
    "Seltos",
    "Sephia",
    "Sorento",
    "Sorento Hybrid",
    "Soul",
    "Soul EV",
    "Spectra",
    "Sportage",
    "Stinger",
    "Telluride",
  ],
  jeep: [
    "Cherokee",
    "Comanche",
    "Commander",
    "Compass",
    "Gladiator",
    "Grand Cherokee",
    "Grand Wagoneer",
    "Liberty",
    "Patriot",
    "Renegade",
    "Wagoneer",
    "Wrangler",
    "Wrangler JK",
  ],
  jaguar: [
    "E-PACE",
    "F-PACE",
    "F-TYPE",
    "I-PACE",
    "S-TYPE",
    "X-TYPE",
    "XE",
    "XF",
    "XJ-Series",
    "XK-Series",
  ],
  isuzu: [
    "Amigo",
    "Ascender",
    "Axiom",
    "Hombre",
    "i-Series",
    "Impulse",
    "Oasis",
    "Pickup",
    "Rodeo",
    "Rodeo Spot",
    "Stylus",
    "Trooper",
    "VehiCROSS",
  ],
  infiniti: [
    "EX",
    "FX",
    "G",
    "G Convertible",
    "G Coupe",
    "G Sedan",
    "I",
    "J",
    "JX",
    "M",
    "Q",
    "Q40",
    "Q50",
    "Q60 Convertible",
    "Q60 Coupe",
    "Q60",
    "Q70",
    "QX",
    "QX4",
    "QX30",
    "QX50",
    "QX60",
    "QX70",
    "QX80",
  ],
  gmc: [
    "Acadia",
    "Canyon",
    "Envoy",
    "Envoy XL",
    "Envoy XUV",
    "Jimmy",
    "R/V 3500 Series",
    "Rally Wagon",
    "S-15",
    "S-15 Jimmy",
    "Safari",
    "Safari Cargo",
    "Savana",
    "Savana Cargo",
    "Sierra 1500",
    "Sierra 1500 Classic",
    "Sierra 1500HD",
    "Sierra 1500HD Classic",
    "Sierra 1500 Limited",
    "Sierra 2500",
    "Sierra 2500 HD",
    "Sierra 2500 HD Classic",
    "Sierra 3500",
    "Sierra 3500 Classic",
    "Sierra C3",
    "Sierra Classic 1500",
    "Sierra Classic 2500",
    "Sierra Classic 3500",
    "Sonoma",
    "Suburban",
    "Syclone",
    "Terrain",
    "Typhoon",
    "Vandura",
    "Yukon",
    "Yukon Hybrid",
    "Yukon XL",
  ],
  honda: [
    "Accord",
    "Accord Crosstour",
    "Accord Hybrid",
    "Accord Plug-in Hybrid",
    "Civic",
    "Civic CRX",
    "Civic del Sol",
    "Clarity",
    "Crosstour",
    "CR-V",
    "CR-V Hybrid",
    "CR-Z",
    "Element",
    "Fit",
    "Fit EV",
    "HR-V",
    "Insight",
    "Odyssey",
    "Passport",
    "Pilot",
    "Prelude",
    "Ridgeline",
    "S2000",
  ],
  hummer: ["H1", "H1 Alpha", "H2", "H2 SUT", "H3", "H3T"],
  hyundai: [
    "Accent",
    "Azera",
    "Elantra",
    "Elantra Coupe",
    "Elantra GT",
    "Elantra Touring",
    "Entourage",
    "Equus",
    "Excel",
    "Genesis",
    "Genesis Coupe",
    "Ioniq Electric",
    "Ioniq Hybrid",
    "Ioniq Plug-in Hybrid",
    "Kona Electric",
    "NEXO",
    "Palisade",
    "Santa Fe",
    "Santa Fe Sport",
    "Santa Fe XL",
    "Scoupe",
    "Sonata",
    "Sonata Hybrid",
    "Sonata Plug-in Hybrid",
    "Tiburon",
    "Tucson",
    "Veloster",
    "Venue",
    "Veracruz",
    "XG300",
    "XG350",
  ],
  others: [],
};

const parts1 = [
  "A-Arm Front Lower",
  "A-Arm Front Upper",
  "A-Arm Rear Lower",
  "A-Arm Rear Upper",
  "AC Accumulator",
  "AC Assembly",
  "AC Blower Motor",
  "AC Compressor",
  "AC Compressor Bracket",
  "AC Compressor Clutch",
  "AC Condenser",
  "AC Condenser Fan",
  "AC Controls",
  "AC Evaporator",
  "AC Evaporator Housing",
  "AC Hose/Line",
  "AC Relay",
  "AC Wiring Harness",
  "Accelerator Cable",
  "Accelerator Control Module",
  "Accelerator Linkage",
  "Air Bag - Driver Door",
  "Air Bag - Passenger Door",
  "Air Bag - Passenger Side Dash",
  "Air Bag Clockspring",
  "Air Bag Control Module",
  "Air Bag Sensor",
  "Air Bag Steering Wheel",
  "Air Box/Air Cleaner",
  "Air Cleaner Housing",
  "Air Flow Meter",
  "Air Intake Distributor",
  "Air Pump",
  "Air Regulator Assembly",
  "Air Ride Compressor",
  "Air Tube/Resonator",
  "Air/Fuel Control Module",
  "Alternator",
  "Alternator Bracket",
  "Amplifier Radio/Speaker",
  "Antenna",
  "Anti Lock Brake Computer",
  "Anti Lock Brake Modulator",
  "Anti Lock Brake Pump",
  "Anti Lock Relay",
  "Anti Lock Sensor",
  "Armrest",
  "Audio Controls",
  "Automatic Transmission Cooler",
  "Axle Assembly Front",
  "Axle Assembly - Rear",
  "Axle Beam Front",
  "Axle Beam Rear",
  "Axle Housing Only",
  "Axle Shaft",
  "Axle Stub Front",
  "Back Glass",
  "Backup Camera",
  "Backup Light",
  "Battery",
  "Battery Box/Tray",
  "Bell Housing",
  "Belt Tensioner",
  "Blower Motor",
  "Body Control Module - BCM",
  "Body Wiring Harness",
  "Brake Booster",
  "Brake Caliper",
  "Brake Drum Front",
  "Brake Drum Rear",
  "Brake Master Cylinder",
  "Brake Proportioning Valve",
  "Brake Relay",
  "Brake Rotor Front",
  "Brake Rotor Rear",
  "Bumper Assembly Front",
  "Bumper Assembly Rear",
  "Bumper Cover Front",
  "Bumper Cover Rear",
  "Bumper Filler Panel",
  "Bumper Impact Absorber Front",
  "Bumper Impact Absorber Rear",
  "Bumper Reinforcement Front",
  "Bumper Reinforcement Rear",
  "Caliper - Brake",
  "Cam Angle Sensor",
  "Cam Position Sensor",
  "Camshaft",
  "Camshaft Housing",
  "Carburetor/Also see Throttlebody",
  "Carpet Front",
  "Carpet Trunk",
  "Carrier Case Only",
  "Carrier/Also see differential",
  "Catalytic Converter",
  "CD Changer",
  "CD Player Radio",
  "Center Cap",
  "Center Console",
  "Center Pillar",
  "Center Post",
  "Charcoal Canister",
  "Chassis Complete",
  "Chassis Control Computer (Not Engine)",
  "Climate Controls",
  "Clock/Gauges/Instrument Cluster",
  "Clutch Disc",
  "Clutch Master Cylinder",
  "Clutch Pressure Plate",
  "Clutch Slave Cylinder",
  "Coil / Ignitor",
  "Coil Spring",
  "Column Shift Lever",
  "Column Steering",
  "Column Switch",
  "Computer Box Not Engine",
  "Computer Box Engine",
  "Condenser",
  "Condenser Fan Blade",
  "Condenser Fan Motor",
  "Condenser/Radiator Cooling Fan",
  "Control Arm Lower Front",
  "Control Arm Upper Front",
  "Control Arm Upper Rear",
  "Control Arm Lower Rear",
  "Conv Top",
  "Conv Top Control Module",
  "Conv Top Lift",
  "Conv Top Motor",
  "Conv Top Relay",
  "Conv Top Switch",
  "Cooling Fan Rad and Con",
  "Cooling Fan Relay",
  "Cowl",
  "Crank Angle Sensor",
  "Crank Position Sensor",
  "Crank Pulley Harmonic Balancer",
  "Crankshaft",
  "Cruise Control Computer",
  "Cylinder Head Engine",
  "Dash Panel",
  "Decklid",
  "Decklid Hinge",
  "Decklid Pull Down Motor",
  "Decklid Strut",
  "Differential Side Gears",
  "Differential Assembly Also see Carrier",
  "Differential Case Only",
  "Differential Flange Only",
  "Distributor",
  "Door Assembly Sliding Door",
  "Door Front Driver",
  "Door Front Passenger",
  "Door Glass Front Driver",
  "Door Glass Front Passenger",
  "Door Glass Rear Driver",
  "Door Glass Rear Passenger",
  "Door Handle Front",
  "Door Handle Rear",
  "Door Hinge",
  "Door Lock Actuator",
  "Door Lock Control Module",
  "Door Mirror Driver",
  "Door Mirror Passenger",
  "Door Molding Front",
  "Door Molding Rear",
  "Door Motor",
  "Door Panel",
  "Door Rear Driver",
  "Door Rear Passenger",
  "Door Regulator Front Driver",
  "Door Regulator Front Passenger",
  "Door Regulator Rear Driver",
  "Door Regulator Rear Passenger",
  "Door Switch Front",
  "Door Vent Glass Front Driver",
  "Door Vent Glass Front Passenger",
  "Door Vent Glass Rear Driver",
  "Door Vent Glass Rear Passenger",
  "Door Vent Glass Regulator Front",
  "Door Vent Glass Regulator Rear",
  "Door Window Motor Front Driver",
  "Door Window Motor Front Passenger",
  "Door Window Motor Rear Driver",
  "Door Window Motor Rear Passenger",
  "Drive Shaft Front",
  "Drive Shaft Rear",
  "Drum Brake Front",
  "Drum Brake Rear",
  "ECU (Engine Control Unit)",
  "ECM (Engine Control Module)",
  "EGR Valve",
  "Electric Door Motor",
  "Electric Window Motor Front Driver",
  "Electric Window Motor Front Passenger",
  "Electric Window Motor Rear Driver",
  "Electric Window Motor Rear Passenger",
  "Emergency Brake Parts",
  "Engine",
  "Engine Block",
  "Engine Computer",
  "Engine Cradle",
  "Engine Crossmember",
  "Engine Cylinder Head",
  "Engine Mount",
  "Engine Oil Cooler",
  "Engine Oil Pan",
  "Engine Wiring Harness",
  "Exhaust Manifold",
  "Exhaust System",
  "Fan Blade",
  "Fan Clutch",
  "Fender",
  "Fender Inner Panel",
  "Fender Molding",
  "Fender Skirt",
  "Flywheel",
  "Fog Lamp Driver",
  "Fog Lamp Passenger",
  "Frame",
  "Front Clip",
  "Fuel Distributor",
  "Fuel Door",
  "Fuel Gauge",
  "Fuel Injector Pump",
  "Fuel Pressure Regulator",
  "Fuel Pump",
  "Fuel Pump Relay",
  "Fuel Rail",
  "Fuel Tank",
  "Fuel Tank Sending Unit",
  "Fuse Box",
  "Gate Window Motor Rear",
  "Gauges/Clock/Instrument Cluster",
  "Glass Back",
  "Glass Front Door Driver",
  "Glass Front Door Passenger",
  "Glass Front Vent Driver",
  "Glass Front Vent Passenger",
  "Glass Rear Door Driver",
  "Glass Rear Door Passenger",
  "Glass Rear Vent Driver",
  "Glass Rear Vent Passenger",
  "Glass Quarter Window",
  "Glove Box",
  "GPS Unit",
  "Grille",
  "Harmonic Balancer Crank Pulley",
  "Header Panel",
  "Headlight Assembly Passenger",
  "Headlight Assembly Driver",
  "Headlight Door Driver",
  "Headlight Door Passenger",
  "Headlight Motor Driver",
  "Headlight Motor Passenger",
  "Headlight Relay",
  "Headlight Switch",
  "Headlight Washer Motor Only Driver",
  "Headlight Washer Motor Only Passenger",
  "Headlight Wiper Motor Only Driver",
  "Headlight Wiper Motor Only Passenger",
  "Headliner",
  "Headrest",
  "Heater Assy",
  "Heater Blower Motor",
  "Heater Controls",
  "Heater Core",
  "Heater Housing",
  "Heater Relay",
  "Hood Hinge",
  "Hood Strut",
  "Horn",
  "Hub",
  "Hub Cap/Wheel Cover",
  "Hub Carrier Rear",
  "Hub Lockout",
  "Idler Arm",
  "Idler Pulley",
  "Ignition Coil",
  "Ignition Ignitor",
  "Ignition Relay",
  "Ignition switch",
  "Independent Rear Suspension Assembly",
  "Instrument Cluster/Gauges",
  "Intake Manifold",
  "Intercooler",
  "Interior Complete",
  "Interior Light Dimmer",
  "Knee Assembly Driver",
  "Knee Assembly Passenger",
  "Knuckle Front",
  "Knuckle Rear",
  "Latches and Locks",
  "Leaf Spring Front",
  "Leaf Spring Rear",
  "Knock Sensor Control Module",
  "License Lamp",
  "Lid/Gate",
  "Lock Actuator",
  "Lock Switch",
  "Lockout Hub 4X4",
  "Lower Control Arm Front",
  "Lower Control Arm Rear",
  "Marker Fog Light Front",
  "Marker Side Light Rear",
  "Mass Air Flow Sensor",
  "Master Cylinder Brake",
  "Master Cylinder Clutch",
  "Message Center",
  "Mirror Door Driver",
  "Mirror Door Passenger",
  "Mirror Rear View",
  "Mirror Switch",
  "Navigation Control Module",
  "Navigation Unit",
  "Oil Cooler",
  "Oil Pan",
  "Oil Pump",
  "Other Part Not Listed",
  "Overdrive Unit Also see Transmission",
  "Owners manual",
  "Oxygen Sensor",
  "Park Lamp Rear (Side)",
  "Park/Fog Lamp Front",
  "Pickup Bed",
  "Pickup Bed Liner",
  "Pickup Bed Rail",
  "Pickup Bed Topper",
  "Pickup Cab",
  "Power Brake Booster",
  "Power Steering Assembly",
  "Power Steering Pump",
  "Power Steering Pump Bracket",
  "Power Window Motor",
  "Power Window Switch",
  "Quarter Panel",
  "Quarter Window Driver",
  "Quarter Window Passenger",
  "Quarter Window Motor Driver",
  "Quarter Window Motor Passenger",
  "Quarter Window Regulator Driver",
  "Quarter Window Regulator Passenger",
  "Radiator",
  "Radiator Core Support",
  "Radiator Fan Clutch",
  "Radiator Overflow Bottle",
  "Radiator Shroud",
  "Radiator/Condensor Mtd. Cooling Fan",
  "Radio/CD Player",
  "Radius Arm Front",
  "Radius Arm Rear",
  "Rear Clip Assembly",
  "Rear Crossmember",
  "Rear Defroster Switch",
  "Rear View Mirror",
  "Reverse Light",
  "Rim",
  "Rim Trim Ring",
  "Ring and Pinion Only",
  "Rocker Arm",
  "Rocker Panel",
  "Roll Bar",
  "Roof Assembly",
  "Roof Rack",
  "Rotor Brake Front",
  "Rotor Brake Rear",
  "Seat Back",
  "Seat Belt Front Driver",
  "Seat Belt Front Passenger",
  "Seat Belt Motor Driver",
  "Seat Belt Motor Passenger",
  "Seat Belt Rear Driver",
  "Seat Belt Rear Passenger",
  "Seat Front Electric",
  "Seat Front Manual",
  "Seat Rear",
  "Seat Third Row",
  "Seat Track Front Only",
  "Shift Lever",
  "Shift Linkage",
  "Shock Absorber",
  "Side Marker Driver",
  "Side Marker Passenger",
  "Side View Mirror",
  "Slave Cylinder",
  "Soft Top",
  "Spare Tire",
  "Speaker",
  "Speedometer",
  "Speedometer Cluster",
  "Spindle",
  "Spoiler Front",
  "Spoiler Rear",
  "Stabilizer Bar Only",
  "Starter",
  "Starter Relay",
  "Starter Solenoid",
  "Steering Box",
  "Steering Column",
  "Steering Knuckle",
  "Steering Rack/Box/Gear",
  "Steering Wheel",
  "Strut Front Driver",
  "Strut Front Passenger",
  "Strut Rear Driver",
  "Strut Rear Passenger",
  "Stub Axle Only Rear",
  "SunRoof Motor",
  "Sunroof Relay",
  "SunRoof/T-Top",
  "Sunvisor",
  "Supercharger/Turbocharger",
  "Suspension Compressor",
  "Suspension Locating Arm Rear",
  "Suspension Trailing Arm Rear",
  "Suspension Rear",
  "Sway Bar",
  "T-Top/Sunroof",
  "Tachometer",
  "Tailgate Hinge",
  "Tailgate/Trunklid",
  "Taillight Driver",
  "Taillight Passenger",
  "Theft Control Module",
  "Thermostat Housing",
  "Third Brake Light",
  "Throttle Actuator",
  "Throttle Body/Throttle Valve Housing",
  "Throttle Position Sensor",
  "Tie Rod",
  "Timing Belt/Chain",
  "Timing Cover",
  "Timing Gears",
  "Tire",
  "Torsion Bar",
  "Tire Carrier",
  "Track bar",
  "Trailer Hitch",
  "Trailing Arm Front",
  "Trailing Arm Lower Rear",
  "Transaxle Housing Only",
  "Transfer Case Assembly",
  "Transfer Case Electric Motor",
  "Transmission",
  "Transmission Bellhousing Only",
  "Transmission Computer",
  "Transmission Cooler",
  "Transmission Mount",
  "Transmission Oil Cooler",
  "Transmission Overdrive Unit",
  "Transmission Pan",
  "Transmission Pump",
  "Transmission Torque Converter",
  "Transverse Arm Front",
  "Transverse Arm Rear",
  "Trunk Lid/Hatch",
  "Trunklid/Hatch Hinge",
  "Turbocharger Supercharger",
  "Turn Signal Light",
  "Turn Signal Relay",
  "Vacuum Pump",
  "Valance Front",
  "Valance Rear",
  "Valve Cover",
  "Voltage Regulator",
  "Washer Reservoir",
  "Water Pump",
  "Water Pump Bracket",
  "Wheel",
  "Wheel Cover/Hubcap",
  "Window Motor",
  "Window Regulator Front",
  "Window Regulator Rear",
  "Window Relay",
  "Window Strut Rear",
  "Window Switch",
  "Window Washer Switch Rear",
  "Window Washer Motor Rear",
  "Window Wiper Switch Rear",
  "Windshield",
  "Windshield Washer Motor",
  "Wiper Arm",
  "Wiper Linkage",
  "Wiper Motor Front Windshield",
  "Wiper Motor Rear",
  "Wiper Relay",
  "Wiper Transmission",
  "Wiring Harness",
];

function updateModels1() {
  // Get the selected brand
  const brand = document.getElementById("car-brand1").value;
  const modelSelect = document.getElementById("car-model1");
  const othersTextArea = document.getElementById("others-textbox");

  if (brand === "others") {
    othersTextArea.removeAttribute("hidden");
    document.getElementById("car-model1").setAttribute("disabled", "");
    document.getElementById("parts1").setAttribute("disabled", "");
  }

  // Clear the existing options in the model dropdown

  // If a brand is selected, populate the models
  if (brand && models1[brand]) {
    models1[brand].forEach((model) => {
      const option = document.createElement("option");
      option.value = model.toLowerCase().replace(/ /g, "-");
      option.textContent = model;
      modelSelect.appendChild(option);
    });
  }
}

const partsField1 = document.getElementById("parts1");

parts1.map((p) => {
  const partList = document.createElement("option");
  partList.value = p;
  partList.innerText = p;
  partsField1.appendChild(partList);
});

document
  .getElementById("animateButton")
  .addEventListener("mouseover", function () {
    document.getElementById("carImage").classList.add("moving");
  });

document
  .getElementById("animateButton")
  .addEventListener("mouseout", function () {
    document.getElementById("carImage").classList.remove("moving");
  });

/*------------------------------------------------------------*/

document.getElementById("brand").addEventListener("change", function () {
  var modelField = document.getElementById("model");
  var partField = document.getElementById("part");
  var otherField = document.getElementById("otherField");

  if (this.value == "other") {
    modelField.disabled = true;
    partField.disabled = true;
    otherField.style.display = "block";
  } else {
    modelField.disabled = false;
    partField.disabled = false;
    otherField.style.display = "none";
  }
});

// --------------popup------------
// Function to copy options from one select element to another
function copyOptions(fromSelect, toSelect) {
  // Clear existing options
  toSelect.innerHTML = "";

  // Clone each option from the original select
  Array.from(fromSelect.options).forEach((option) => {
    const clonedOption = option.cloneNode(true);
    toSelect.appendChild(clonedOption);
  });
}

// Sync options on page load
document.addEventListener("DOMContentLoaded", function () {
  copyOptions(
    document.getElementById("year-field"),
    document.getElementById("year-field-popup")
  );
  copyOptions(
    document.getElementById("car-brand1"),
    document.getElementById("car-brand1-popup")
  );
  copyOptions(
    document.getElementById("car-model1"),
    document.getElementById("car-model1-popup")
  );
  copyOptions(
    document.getElementById("parts1"),
    document.getElementById("parts1-popup")
  );
});

function popupValues() {
  copyOptions(
    document.getElementById("year-field"),
    document.getElementById("year-field-popup")
  );
  copyOptions(
    document.getElementById("car-brand1"),
    document.getElementById("car-brand1-popup")
  );
  copyOptions(
    document.getElementById("car-model1"),
    document.getElementById("car-model1-popup")
  );
  copyOptions(
    document.getElementById("parts1"),
    document.getElementById("parts1-popup")
  );
}

// function popupValues3() {
//   let yearOne = document.getElementById("year-field").value;
//   let brandOne = document.getElementById("car-brand1").value;
//   let modelOne = document.getElementById("car-model1").value;
//   let partOne = document.getElementById("parts1").value;

//   let continueBtn = document.getElementById("continueButton");
//   if (!yearOne || !brandOne || !modelOne || !partOne) {
//     alert("Fill all fields in form ");
//   } else {
//     let yearPopup = document.getElementById("year-field-popup");
//     let modelPopup = document.getElementById("car-model1-popup");
//     let partPopup = document.getElementById("parts1-popup");

//     let yearPopupOption = document.createElement("option");
//     yearPopupOption.textContent = yearOne;
//     yearPopupOption.setAttribute("selected", "selected");
//     yearPopupOption.appendChild(yearPopup);

//     let modelPopupOption = document.createElement("option");
//     modelPopupOption.textContent = modelOne;
//     modelPopupOption.setAttribute("selected", "selected");
//     modelPopup.appendChild(modelPopupOption);

//     let partPopupOption = document.createElement("option");
//     partPopupOption.textContent = partOne;
//     partPopupOption.setAttribute("selected", "selected");
//     partPopup.appendChild(partPopupOption);

//     let brandPopup = document.getElementById("car-brand1-popup");
//     let brandPopupOption = document.createElement("option");
//     brandPopupOption.textContent = brandOne;
//     brandPopupOption.setAttribute("selected", "selected");
//     brandPopup.appendChild(brandPopupOption);

//     continueBtn.setAttribute("data-bs-toggle", "modal");
//   }
// }

// ------------------------------validation code-------------------

function validateName() {
  let nameField = document.getElementById("full-name").value;
  let nameMessage = document.getElementById("name-message");
  const namePattern = /^[A-Za-z\s]+$/;
  if (namePattern.test(nameField)) {
    nameMessage.hidden = true;
  } else {
    nameMessage.hidden = false;
  }
}

function validateEmail() {
  const emailInput = document.getElementById("email-field").value;
  const emailMessage = document.getElementById("email-message");
  const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

  if (emailPattern.test(emailInput)) {
    emailMessage.hidden = true;
  } else {
    emailMessage.hidden = false;
  }
}

function validatePhone() {
  const phoneInput = document.getElementById("phone-number").value;
  const phoneMessage = document.getElementById("phone-message");
  const phonePattern = /^(?:\(\d{3}\)\s?|\d{3}[-.\s]?|)\d{3}[-.\s]?\d{4}$/;

  if (phonePattern.test(phoneInput)) {
    phoneMessage.hidden = true;
  } else {
    phoneMessage.hidden = false;
  }
}

function validatePincode() {
  const pincodeInput = document.getElementById("pincode").value;
  const pincodeMessage = document.getElementById("pincode-message");
  const pincodePattern = /^\d{5}$/;
  if (pincodePattern.test(pincodeInput)) {
    pincodeMessage.hidden = true;
  } else {
    pincodeMessage.hidden = false;
  }
}

function validateNamePopup() {
  const nameInput = document.getElementById("full-name-popup").value;
  const nameMessage = document.getElementById("name-message-popup");
  const namePattern = /^[A-Za-z\s]+$/; // Regex for letters and spaces only

  if (namePattern.test(nameInput)) {
    nameMessage.hidden = true; // Hide the message if valid
  } else {
    nameMessage.hidden = false; // Show the message if invalid
  }
}

function validateEmailPopup() {
  const emailInput = document.getElementById("email-popup").value;
  const emailMessage = document.getElementById("email-message-popup");
  const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/; // Regex for valid email format

  if (emailPattern.test(emailInput)) {
    emailMessage.hidden = true; // Hide the message if valid
  } else {
    emailMessage.hidden = false; // Show the message if invalid
  }
}

function validatePhonePopup() {
  const phoneInput = document.getElementById("phone-popup");
  const phoneMessage = document.getElementById("phone-message-popup");
  const phoneNumber = phoneInput.value;

  // Basic phone number validation regex (adjust as necessary)
  const phoneRegex = /^[0-9]{10}$/; // Example: 10-digit numbers only

  if (phoneRegex.test(phoneNumber)) {
    phoneMessage.hidden = true; // Hide error message
  } else {
    phoneMessage.hidden = false; // Show error message
  }
}

function validatePincodePopup() {
  const pinInput = document.getElementById("pin-popup");
  const pinMessage = document.getElementById("pincode-message-popup");
  const pinCode = pinInput.value;

  // Basic pin code validation regex (adjust as necessary)
  const pinRegex = /^[0-9]{5}$/; // Example: 6-digit pin codes only

  if (pinRegex.test(pinCode)) {
    pinMessage.hidden = true; // Hide error message
  } else {
    pinMessage.hidden = false; // Show error message
  }
}
